export type Client = {
  id: string;
  razaoSocial: string;
  segmento: string | null;
  endereco: string | null;
  cnpj: string | null;
  telefone: string | null;
  email: string | null;
  instagram: string | null;
  servicosSugeridos: string | null;
  statusContato: string | null;
  prioridade: string | null;
  fonte: string | null;
};

// Importado de prospeccao_campo_limpo_100_estabelecimentos.xlsx (aba "Leads").
// Lista de prospecção — dados reais de contato (e-mail/Instagram) só quando encontrados
// em fontes públicas. Usado como carga inicial (seed) da tabela `clients` do Supabase
// na primeira vez que a área de Clientes é aberta com o banco vazio.
export const LEADS_SEED: Client[] = [
  {
    id: "18",
    razaoSocial: "Academia Corpo & Alma Fitness",
    segmento: "Academia",
    endereco: "Rua Carum, 51 - Sala 1 - Jardim Maria Duarte, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Campanhas de matrícula + conteúdo + landing page",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "19",
    razaoSocial: "Academia Radan",
    segmento: "Academia",
    endereco: "Rua Américo Falcão, 33 - Vila Pirajussara, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego para matrículas + design + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "20",
    razaoSocial: "Academia Raia Sul",
    segmento: "Academia",
    endereco: "Rua Domingos Bicudo, 579 - Vila Pirajussara, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego pago + campanhas de planos + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "75",
    razaoSocial: "Águia de Fogo Automóveis",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 4570 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego para leads + site de estoque + criativos",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "59",
    razaoSocial: "Águia Shoes - Calçados",
    segmento: "Calçados",
    endereco: "Estrada do Campo Limpo, 4263 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + anúncios + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "51",
    razaoSocial: "Alfino's Café e Grill",
    segmento: "Restaurante/churrascaria",
    endereco: "Rua Nossa Senhora do Bom Conselho, 299 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + anúncios + identidade visual",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "60",
    razaoSocial: "American Shoes - Calçados",
    segmento: "Calçados",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Criativos + tráfego + campanhas de coleção",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "24",
    razaoSocial: "Ane & Clã Comércio de Roupas Infanto Juvenil",
    segmento: "Moda infantil",
    endereco: "Estrada do Campo Limpo, 4213A - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo digital + anúncios + e-commerce/landing page",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "1",
    razaoSocial: "Arte Bella",
    segmento: "Salão de beleza",
    endereco: "Rua Ivar Beckman, 117 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + conteúdo para Instagram + tráfego local",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "92",
    razaoSocial: "Ateliê da Bijoux",
    segmento: "Bijuterias/acessórios",
    endereco: "Rua Kunito Miyasaka, 105 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + catálogo + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "93",
    razaoSocial: "Ateliê Maria Chica",
    segmento: "Bijuterias/acessórios",
    endereco: "Rua Doutor Clóvis de Oliveira, 518 - Jardim Guedala, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "loja@ateliemariachica.com.br",
    instagram: "@ateliemariachicabr",
    servicosSugeridos: "Conteúdo + catálogo + anúncios",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "2",
    razaoSocial: "Atual Hair",
    segmento: "Salão de beleza",
    endereco: "Estrada Pirajussara à Valo Velho, 1319 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Gestão de Instagram + tráfego pago + identidade visual",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "25",
    razaoSocial: "Bahadely Modas",
    segmento: "Moda",
    endereco: "Estrada do Campo Limpo, 4441 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design de catálogo + tráfego pago + Instagram",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "3",
    razaoSocial: "Beauty Sul",
    segmento: "Salão de beleza",
    endereco: "Rua Nossa Senhora do Bom Conselho, 299 - Loja 24/25 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + anúncios para agendamento + design",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "61",
    razaoSocial: "Beneri - Calçados",
    segmento: "Calçados",
    endereco: "Estrada do Campo Limpo, 4027 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo digital + Instagram + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "99",
    razaoSocial: "Botocenter Campo Limpo",
    segmento: "Clínica de estética",
    endereco: "Estrada do Campo Limpo, 459 - Vila Prel, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego para avaliação + conteúdo + campanhas",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "76",
    razaoSocial: "Brun Car Automóveis",
    segmento: "Automóveis",
    endereco: "Rua Pedrina Maria da Silva Valente, 100 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Google/Meta Ads + catálogo de veículos + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "84",
    razaoSocial: "Buquê de Casamento Nobre",
    segmento: "Eventos/casamentos",
    endereco: "Rua Tauna, 100 - Jardim Leônidas Moreira, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "lembrancinhasdecasamentonobre@gmail.com",
    instagram: null,
    servicosSugeridos: "Identidade visual + Instagram + anúncios para noivas",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "13",
    razaoSocial: "Cacau Dog",
    segmento: "Pet shop",
    endereco: "Rua Nossa Senhora do Bom Conselho, 299 - Loja 22 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + campanhas locais + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "62",
    razaoSocial: "Calçados Sergio de Campo Limpo",
    segmento: "Calçados",
    endereco: "Estrada do Campo Limpo, 4092 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + campanhas locais + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "85",
    razaoSocial: "Caverna Bar e Eventos",
    segmento: "Eventos/bar",
    endereco: "Rua Américo Falcão, 107 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "caverna.bar@hotmail.com",
    instagram: null,
    servicosSugeridos: "Campanhas de eventos + conteúdo + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "26",
    razaoSocial: "Célia Satomi Fukuda",
    segmento: "Moda",
    endereco: "Estrada do Campo Limpo, 4550 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + conteúdo + anúncios",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "39",
    razaoSocial: "Center Paes Morumbi Sul",
    segmento: "Padaria",
    endereco: "Rua Nossa Senhora do Bom Conselho, 299 - Loja 1 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo gastronômico + tráfego local + Google",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "86",
    razaoSocial: "CONTATO FESTAS",
    segmento: "Eventos",
    endereco: "Rua João Bernardo Vieira, 000 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Site + identidade visual + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "87",
    razaoSocial: "Criaplan",
    segmento: "Eventos",
    endereco: "Rua Carlos Magalhães, 100 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + site + geração de leads",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "63",
    razaoSocial: "Di Gaspi - Calçados",
    segmento: "Calçados",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Mídia paga + criativos + campanhas sazonais",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "50",
    razaoSocial: "Divino Fogão",
    segmento: "Restaurante",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego local + criativos + campanhas promocionais",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "77",
    razaoSocial: "Drikar Comércio de Veículos",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 4646 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Landing page + tráfego + criativos",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "64",
    razaoSocial: "Eliana Aparecida Sacramento Tabatini Calçados",
    segmento: "Calçados",
    endereco: "Avenida Carlos Lacerda, 141 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + catálogo + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "49",
    razaoSocial: "Empada Caipira",
    segmento: "Restaurante",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo gastronômico + tráfego + campanhas sazonais",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "55",
    razaoSocial: "Espaço Árabe - Panamby",
    segmento: "Restaurante",
    endereco: "Rua José Ramon Urtiza, 975 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "panamby@espacoaraberestaurante.com.br",
    instagram: null,
    servicosSugeridos: "Tráfego pago + conteúdo + site/delivery",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "53",
    razaoSocial: "Estação do Chopp",
    segmento: "Bar/restaurante",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + campanhas de eventos + tráfego",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "78",
    razaoSocial: "Estilo Veículos",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 2899 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Anúncios de estoque + site + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "14",
    razaoSocial: "Fauna & Flora Pet Shop",
    segmento: "Pet shop",
    endereco: "Estrada do Campo Limpo, 5796 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego pago + catálogo visual + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "21",
    razaoSocial: "FF Academia",
    segmento: "Academia",
    endereco: "Rua Roque de Mingo, 49 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + anúncios locais + identidade visual",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "22",
    razaoSocial: "Flavio Augusto de Oliveira Fitness",
    segmento: "Academia",
    endereco: "Rua Roque de Mingo, 49 - Jardim Samara, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Marca pessoal + conteúdo + tráfego pago",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "88",
    razaoSocial: "Flavio Souza - Cabine de Fotos",
    segmento: "Eventos",
    endereco: "Rua Américo Falcão, 417 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "flafotocabine@gmail.com",
    instagram: "Instagram não localizado com segurança",
    servicosSugeridos: "Conteúdo visual + tráfego + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "27",
    razaoSocial: "Fórmula Mix Moda",
    segmento: "Moda",
    endereco: "Avenida Carlos Lacerda, 191 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + tráfego pago + criação de site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "4",
    razaoSocial: "Fran Cabeleireiro",
    segmento: "Salão de beleza",
    endereco: "Rua Giovanni Amadeo, 51 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + conteúdo + tráfego local",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "65",
    razaoSocial: "Gamacao Com Calçados Roupas e Acessórios",
    segmento: "Moda/calçados",
    endereco: "Estrada do Campo Limpo, 4903 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + catálogo + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "94",
    razaoSocial: "Giovanna Bijoux",
    segmento: "Bijuterias/acessórios",
    endereco: "Shopping Campo Limpo - Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + criativos + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "52",
    razaoSocial: "Giraffa's",
    segmento: "Restaurante",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Campanhas locais + criativos + mídia paga",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "95",
    razaoSocial: "GiselleBoutiqueBR",
    segmento: "Semijoias/papelaria",
    endereco: "Rua Caranapatuba, 115 - Jardim Umarizal, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "gisellezajac98@gmail.com",
    instagram: "@giselleboutiquebr",
    servicosSugeridos: "Catálogo + tráfego pago + identidade visual",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "97",
    razaoSocial: "Iolita Concept",
    segmento: "Loja de roupas",
    endereco: "Rua Lourenço Saporito, 353 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + conteúdo + tráfego para WhatsApp",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "89",
    razaoSocial: "JHOS Jackson Produções e Eventos",
    segmento: "Eventos",
    endereco: "Rua Sancho Garcia, 8 - Casa 2 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade + portfólio online + anúncios",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "5",
    razaoSocial: "JR Cabeleireiros",
    segmento: "Salão de beleza",
    endereco: "Rua Canabarro, 17 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + anúncios + criação de site/landing page",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "56",
    razaoSocial: "Lanchonete e Restaurante Saboriar",
    segmento: "Restaurante/lanchonete",
    endereco: "Rua Mário Neme, 41 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + anúncios locais + cardápio digital",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "28",
    razaoSocial: "LJ Confecções",
    segmento: "Confecções",
    endereco: "Avenida Carlos Lacerda, 1634 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + catálogo + campanhas de conversão",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "29",
    razaoSocial: "Loja de Confecções Nica",
    segmento: "Confecções",
    endereco: "Estrada do Campo Limpo, 4015 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + tráfego pago + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "100",
    razaoSocial: "Lojadasu Moda Feminina",
    segmento: "Moda feminina",
    endereco: "Rua Alves dos Santos, 194 - Jardim Jamaica, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + catálogo + tráfego pago",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "30",
    razaoSocial: "Lucgil",
    segmento: "Moda",
    endereco: "Rua Doutor Nelson de Souza Campos, 133 - Jardim Nadir, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Reposicionamento + conteúdo + anúncios",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "66",
    razaoSocial: "Luiz Henrique da Cruz Sene Calçados",
    segmento: "Calçados",
    endereco: "Rua Adolfo Campos de Araújo, 10 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + anúncios + presença local",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "31",
    razaoSocial: "Macedo S Fashion Comércio do Vestuário",
    segmento: "Moda",
    endereco: "Estrada do Campo Limpo, 4237 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + tráfego pago + identidade visual",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "67",
    razaoSocial: "Mad's Bazar Confecções e Calçados",
    segmento: "Moda/calçados",
    endereco: "Rua Doutor Renato Bueno Neto, 52 - Jardim Catanduva, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + catálogo + anúncios",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "96",
    razaoSocial: "Magazine Paris",
    segmento: "Moda/acessórios",
    endereco: "Estrada do Campo Limpo, 2233 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + catálogo + campanhas",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "32",
    razaoSocial: "Marilene Inocêncio",
    segmento: "Moda/bazar",
    endereco: "Rua Eliane Araujo Neves, 352 - Jardim Catanduva, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + conteúdo + campanhas locais",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "33",
    razaoSocial: "Marisa Alves Lima Bazar",
    segmento: "Bazar",
    endereco: "Avenida Sílvio Ribeiro Aragão, 707 - Vila Franca, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo para WhatsApp + tráfego + identidade visual",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "34",
    razaoSocial: "Mary",
    segmento: "Moda",
    endereco: "Largo do Campo Limpo, 4432 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + anúncios + catálogo digital",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "79",
    razaoSocial: "NEF Veículos",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 2332 - Vila Prel, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego pago + catálogo + remarketing",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "35",
    razaoSocial: "Negrão Moda Jovem",
    segmento: "Moda jovem",
    endereco: "Estrada do Campo Limpo, 4355 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + tráfego pago + e-commerce",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "80",
    razaoSocial: "Newline Automóveis",
    segmento: "Automóveis",
    endereco: "Largo do Campo Limpo, 675 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Site de estoque + Google Ads + criativos",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "6",
    razaoSocial: "Ninas Cabeleireiros",
    segmento: "Salão de beleza",
    endereco: "Rua Jorge Ozi, 87 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + conteúdo + campanhas de WhatsApp",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "68",
    razaoSocial: "Ninki Magazine - Calçados",
    segmento: "Calçados",
    endereco: "Estrada do Campo Limpo, 4102 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego pago + design + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "69",
    razaoSocial: "Nog Shoes Comércio de Calçados e Acessórios",
    segmento: "Calçados/acessórios",
    endereco: "Rua Mario Neme, 286 - Jardim Samara, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + catálogo + tráfego",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "36",
    razaoSocial: "Nova Orleans Comércio de Confecções",
    segmento: "Confecções",
    endereco: "Estrada do Campo Limpo, 4585 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + catálogo + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "15",
    razaoSocial: "Onix Castanheira Pet Shop",
    segmento: "Pet shop",
    endereco: "Rua Alves dos Santos, 168 - Jardim Jamaica, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + tráfego local + Google/Maps",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "40",
    razaoSocial: "Padaria e Confeitaria Marilia",
    segmento: "Padaria/confeitaria",
    endereco: "Praça Marília, s/n - Jardim Umarizal, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Fotografia/design de produtos + anúncios + delivery",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "41",
    razaoSocial: "Padaria e Confeitaria San Vitor",
    segmento: "Padaria/confeitaria",
    endereco: "Avenida Doutor João Guimarães, 734 - Jardim Taboão, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + tráfego local + identidade visual",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "42",
    razaoSocial: "Panificadora Confeitaria Casa de Carnes JMJ",
    segmento: "Padaria/casa de carnes",
    endereco: "Estrada do Campo Limpo, 5065 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + ofertas + tráfego pago",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "43",
    razaoSocial: "Panificadora e Confeitaria Deziderio Ferreira",
    segmento: "Padaria/confeitaria",
    endereco: "Estrada do Campo Limpo, 4609 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design promocional + anúncios + Google",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "44",
    razaoSocial: "Panificadora e Confeitaria Estrela Cadente",
    segmento: "Padaria/confeitaria",
    endereco: "Avenida Sílvio Ribeiro Aragão, 101 - Vila Franca, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + tráfego local + identidade",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "45",
    razaoSocial: "Panificadora e Confeitaria Simone",
    segmento: "Padaria/confeitaria",
    endereco: "Avenida Carlos Lacerda, 152 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Social media + campanhas de ofertas + site",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "46",
    razaoSocial: "Panificadora Flor do Jardim Helga",
    segmento: "Padaria",
    endereco: "Rua Nelson Lomanto, 46 - Jardim Helga, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego local + conteúdo + Google Business",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "47",
    razaoSocial: "Panificadora Rainha do Rosana",
    segmento: "Padaria",
    endereco: "Avenida Carlos Lacerda, 1655 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + tráfego pago + delivery",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "48",
    razaoSocial: "Panificadora Sol de Ipanema",
    segmento: "Padaria",
    endereco: "Rua Maniçoba, 20 - Jardim Umarizal, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + campanhas locais + site",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "54",
    razaoSocial: "Pattroni Pizzaria",
    segmento: "Pizzaria",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego para delivery + design de cardápio + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "7",
    razaoSocial: "Personal Hair Studio",
    segmento: "Salão de beleza",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Campanhas locais + conteúdo + peças promocionais",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "16",
    razaoSocial: "Pet Shop Parque Regina",
    segmento: "Pet shop",
    endereco: "Rua Antonio José Bastos, 43 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + anúncios para serviços + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "90",
    razaoSocial: "Qualificados Brasil Eventos",
    segmento: "Eventos",
    endereco: "Rua Clarimundo Gonçalves, 36 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Site + tráfego B2C + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "23",
    razaoSocial: "Raia Sul Sports",
    segmento: "Academia",
    endereco: "Rua Domingos Bicudo, 579 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Campanhas de matrícula + social media + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "57",
    razaoSocial: "Restaurante do Alemão",
    segmento: "Restaurante",
    endereco: "Rua Professora Nina Stocco, 88 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + tráfego local + Google",
    statusContato: "prospectar",
    prioridade: "Média",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "81",
    razaoSocial: "RR Multimarcas",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 4636 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Meta Ads + Google Ads + landing page",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "8",
    razaoSocial: "Salão B de Cabeleleiro Charme",
    segmento: "Salão de beleza",
    endereco: "Rua do Criptônio, 2690 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + conteúdo + tráfego pago",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "98",
    razaoSocial: "Salão de Beleza Bella Donna",
    segmento: "Salão de beleza",
    endereco: "Rua Domingos Bicudo, 581 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Conteúdo + tráfego local + site/landing page",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "9",
    razaoSocial: "Salão Preferência",
    segmento: "Salão de beleza",
    endereco: "Rua Giovanni Amadeo, 61 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Gestão de redes + anúncios locais + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "37",
    razaoSocial: "Saxton & Scavia Confecções",
    segmento: "Confecções",
    endereco: "Rua Mieres, 50 - Jardim São Januário, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Identidade visual + anúncios + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "10",
    razaoSocial: "Sergio & Waldir Cabeleireiros",
    segmento: "Salão de beleza",
    endereco: "Rua Ivar Beckman, 97 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + Google/Meta Ads + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "11",
    razaoSocial: "Shirley Cabeleireira",
    segmento: "Salão de beleza",
    endereco: "Rua Viegas Xortes, 300 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: "atendimento@shirleycabeleireira.com",
    instagram: "@shirleypereiracabeleireira",
    servicosSugeridos: "Tráfego para agendamentos + conteúdo + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "82",
    razaoSocial: "Sobrauto Automóveis",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 4670 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego para WhatsApp + site + criativos",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "38",
    razaoSocial: "Sparapan Comércio e Confecções",
    segmento: "Confecções",
    endereco: "Rua Mario Linhares, 34 - Jardim Ingá, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + tráfego + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "58",
    razaoSocial: "Sr Malbek Marmitex",
    segmento: "Marmitex/delivery",
    endereco: "Rua Monforte de Lemos - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego para delivery + cardápio digital + criativos",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "12",
    razaoSocial: "Styllo Mulher",
    segmento: "Salão de beleza",
    endereco: "Rua Afonso Domingues, 37 - Jardim Macedonia, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Reposicionamento visual + conteúdo + tráfego local",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "71",
    razaoSocial: "Tennis One - Calçados",
    segmento: "Calçados",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo + anúncios + conteúdo",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "70",
    razaoSocial: "Tennis Station - Calçados",
    segmento: "Calçados",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Campanhas de produtos + criativos + mídia",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "91",
    razaoSocial: "Terezinha Buffet e Decoração",
    segmento: "Buffet/eventos",
    endereco: "Rua Martinho Lutero, 58 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Portfólio digital + Instagram + tráfego",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "72",
    razaoSocial: "Tunoda Calçados",
    segmento: "Calçados",
    endereco: "Estrada do Campo Limpo, 4092 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + tráfego + catálogo digital",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "73",
    razaoSocial: "Verona Calçados",
    segmento: "Calçados",
    endereco: "Rua Adolfo Campos de Araújo, 10 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Instagram + campanhas + site",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "83",
    razaoSocial: "W.K.I. Veículos",
    segmento: "Automóveis",
    endereco: "Estrada do Campo Limpo, 6285 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Catálogo digital + tráfego pago + remarketing",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "74",
    razaoSocial: "World Tennis - Calçados",
    segmento: "Calçados",
    endereco: "Shopping Campo Limpo, Estrada do Campo Limpo, 459 - São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Tráfego pago + criativos + campanhas sazonais",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
  {
    id: "17",
    razaoSocial: "Xodó Animais",
    segmento: "Pet shop",
    endereco: "Rua Mário Neme, 50 - Campo Limpo, São Paulo - SP",
    cnpj: null,
    telefone: null,
    email: null,
    instagram: null,
    servicosSugeridos: "Design + campanhas sazonais + tráfego pago",
    statusContato: "prospectar",
    prioridade: "Alta",
    fonte: "Diretórios públicos / busca web — validar antes do contato",
  },
];

